server:
  port: ${PORT:8080}

logging:
  file:
    name: cx-flow.log

cx-flow:
  token: xxxx
  bug-tracker: NONE
  bug-tracker-impl:
    - GitHub
    - Azure
    - GitLab
  branches:
    - develop
    - master
    - security
  filter-severity:
    - High
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  wiki-url: https://checkmarx.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://cxa.codebashing.com/courses/
  auto-profile: true

checkmarx:
  username: xxx
  password: xxx
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: https://localhost:8100
  url: ${checkmarx.base-url}/cxrestapi
  multi-tenant: true
  incremental: true
  scan-preset: Checkmarx Default
  configuration: Default Configuration
  team: \CxServer\SP\Checkmarx
  scan-timeout: 120
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx

github:
  webhook-token: 1234
  token: xxx
  url: https://github.com
  api-url: https://api.github.com/repos/
  block-merge: true
  error-merge: true
  cx-summary: true